[default]
src = 'contracts'
out = 'artifacts'
libs = ['lib']
remappings = [
    '@ensdomains/=node_modules/@ensdomains/',
    '@eth-optimism/=node_modules/@eth-optimism/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    'eth-gas-reporter/=node_modules/eth-gas-reporter/',
    'hardhat/=node_modules/hardhat/',
    'openzeppelin-solidity-2.3.0/=node_modules/openzeppelin-solidity-2.3.0/',
    'ds-test/=lib/forge-std/lib/ds-test/src/',
    'forge-std/=lib/forge-std/src/',
]
# libraries = [
#     "contracts/libraries/MerkleTree.sol:MerkleTree:0x70B0D8c1a00B937Cbb08DcA33812670D235157Bc",
#     "contracts/libraries/AelinAllowList.sol:AelinAllowList:0xAA837deD11f623F6F56d03A5496FA6af71E6c9F5",
#     "contracts/libraries/AelinNftGating.sol:AelinNftGating:0x103Dc458C4CEb1B47A4CF031919e426218a34048"
# ]
fuzz_max_global_rejects = 50000000

# See more config options https://github.com/foundry-rs/foundry/tree/master/config